### ISSUE TITLE
[FEAT] 토큰이 남아있는 이슈 해결 및 공유하기 기능 수정

### ISSUE THREAD

**Issue by ryuchanghwi** [U-is-Ni-in-Korea/iOS-United#107]
## 📝  To-do

- [x] 토큰이 남아있는 이슈 해결
- [x]  온보딩 버튼 글자 수정
- [x] 연결 확인하기 이미지 색상 수정
