### ISSUE TITLE
[FEAT] 소원권 QA 수정사항

### ISSUE THREAD

**Issue by dumpwithlove** [U-is-Ni-in-Korea/iOS-United#110]
## 📝  To-do

- [x] 상대 소원권 타이틀 동적 변하게
- [x] 상대 소원권 칩스 텍스트 변경
- [x] 새소원권 nil 일 경우 다음 화면 넘어가지 않도록
