### ISSUE TITLE
[FEAT] Timer 기능 및 뷰 연결

### ISSUE THREAD

**Issue by yuujjeong** [U-is-Ni-in-Korea/iOS-United#162]
## 📝  To-do

- [ ] 작동중 취소버튼 Alert
- [ ] 뷰 연결
- [ ] 종료 시 초기 화면 이동
- [ ] 종료 시 토스트 메시지
- [ ] 알림음 변경
