### ISSUE TITLE
[FEAT] 한판 승부 화면 전환 수정

### ISSUE THREAD

**Issue by ryuchanghwi** [U-is-Ni-in-Korea/iOS-United#176]
## 📝  To-do

홈에서 한판 승부 버튼을 눌렀을 때 나타나는 3개의 화면 연결하기
- [x] 게임 정하기 화면
- [x] 승부 결과 입력 화면
- [x] 승부 결과 확인 화면
