### ISSUE TITLE
[FEAT] 타이머 디테일 수정

### ISSUE THREAD

**Issue by yuujjeong** [U-is-Ni-in-Korea/iOS-United#190]
## 📝  To-do

- [ ] 타이머 종료 소리
- [ ] 토스트 메시지 디자인 및 안사라지는 문제
- [ ] 화면 꺼도 진행
