### ISSUE TITLE
[FEAT] NetworkPlatform, Domain 모듈 분리

### ISSUE THREAD

**Issue by ryuchanghwi** [U-is-Ni-in-Korea/iOS-United#269]
## 📝  To-do

- [x] NetworkPlatform 모듈 분리
- [x] Domain 모듈 분리
- [x] 의존 관계 정리
