### ISSUE TITLE
[FEAT] 히스토리 남은 UI 및 기능 구현

### ISSUE THREAD

**Issue by dumpwithlove** [U-is-Ni-in-Korea/iOS-United#42]
## 📌  Feature Issue

히스토리 뷰 남은 UI 및 기능 구현 이슈입니다

## 📝  To-do

- [x] 네비바 백버튼 액션
- [x] Empty 뷰 이미지 추가
- [x] 상세 히스토리 미션 공개 UI
