### ISSUE TITLE
[FEAT] 마이페이지 디자인 수정 사항 반영

### ISSUE THREAD

**Issue by yuujjeong** [U-is-Ni-in-Korea/iOS-United#54]
## 📌  Feature Issue
프로필 수정 저장버튼 만들기

## 📝  To-do

- [ ] 마이페이지 프로필 이메일 없어짐
- [ ] 설정 -> 마이페이지로 이름 바뀜
- [ ] 프로필 수정에서 이메일 없어짐
- [ ] 닉네임 텍스트필드 회색 레이아웃 없음
